site_name: yarPPG
theme:
    name: material
    palette:
        scheme: default
extra_css:
  - style.css
nav:
  - Getting started: index.md
  - Deep dive: deepdive.py
  - reference/rppg.md
  - ROI detection:
    - reference/roi/index.md
    - reference/roi/facemesh_detector.md
  - reference/processors.md
  - reference/hr_calculator.md

plugins:
  - search
  - section-index
  - autorefs
  - mkdocstrings:
      default_handler: python
  - mkdocs-jupyter:
      ignore_h1_titles: True
      execute: false

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
