select = ["E", "F", "PL", "N", "D", "ARG", "I"]
ignore = [
    "D105",    # undocumented-magic-method,
    "D107",    # undocumented-public-init
    "PLR2004", # magic-value-comparison,
]
ignore-init-module-imports = true
line-length = 88
src = ["src/yarppg"]
exclude = [
    "__pypackages__",
    "_build",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git-rewrite",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
[per-file-ignores]
"__init__.py" = ["F401"] # unused-import
"tests/*.py" = ["D"]     # no docs needed in tests.

[pydocstyle]
convention = "google"

[pylint]
max-args = 10
